name: Notify Discord on PR

on:
  pull_request:
    types: [opened]

jobs:
  discordNotification:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Discord
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{
                 "username": "GitHub Bot",
                 "content": "📣 A new Pull Request was opened: **${{ github.event.pull_request.title }}**\n👉 URL: ${{ github.event.pull_request.html_url }}"
               }' \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
