name: Notify Discord on PR Open

on:
  pull_request:
    types: [opened]

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send PR Notification to Discord
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{\"content\": \"📢 **New PR:** [${{ github.event.pull_request.title }}](${{ github.event.pull_request.html_url }}) by **${{ github.actor }}**\"}" \
            ${{ secrets.DISCORD_WEBHOOK_URL }}
